doc/index.md, src/android/StatusBar.java
Since Android Lollipop the statusbar of your app is no longer black. On a Samsung Galaxy S5 my mostly white app now has a blue statusbar. This change gives control back to your app.
=> Allow setting the statusbar backgroundcolor on Android

doc/index.md
The default value is no longer black. (CB-7486)
=> update docs for StatusBarBackgroundColor

src/android/StatusBar.java
This change is fix for the following warning message at startup:
W/CordovaPlugin( 6470): Attempted to send a second callback for ID:
StatusBar1091036409
W/CordovaPlugin( 6470): Result was: "Invalid action"
=> fix warning message

src/ios/CDVStatusBar.m
Fix for the incorrectly calculated statusbar height, when hiding the statusbar in landscape orientation in iOS 8.
At first I thought I use the IsAtLeastiOSVersion macro, but then I noticed it had already been tested in https://issues.apache.org/jira/browse/CB-7549, so I replaced it with a more fool proof solution..
=> CB-9214 - [iOS] Landscape webview height is calculated wrong

src/ios/CDVStatusBar.m
Changed UIDeviceOrientationIsLandscape(orientation) to UIInterfaceOrientationIsLandscape([[UIApplication sharedApplication] statusBarOrientation], fix the warning and is more reliable.
Changed UIStatusBarStyleBlackTranslucent and UIStatusBarStyleBlackOpaque to UIStatusBarStyleLightContent as apple recommends, it does the same thing, but it was doing the same before changing. Kept compatibility with iOS 6
Just removed the self.viewController.wantsFullScreenLayout lines, didn't seem to do anything
=> CB-9250 Fix iOS warnings in Statusbar plugin

src/ios/CDVStatusBar.m
Fixes CB-4712, CB-5439 and hopefully all the statusbar issues related
to the size or resize of the cordova webview when the status bar
changes the size and/or rotation
=> Fixes CB-4712, CB-5439 statusbar issues

src/ios/CDVStatusBar.m
We don’t allow the statusbar to overlay the webview on iOS 6, but in
some cases it happens. This changes avoid it.
=> Fix for CB-10752 status bar overlays the webview on iOS 6 in some cases

src/ios/CDVStatusBar.m
This PR fix the webview resize problem when a popover is present
iOS
Fixes CB-11485 
Tested on iOS 7, 8 and 9 iPads when a popover is present
- [] Added automated test coverage as appropriate for this change.
=> CB-11485: (ios) fix resize on rotation with popover

src/ios/CDVStatusBar.m
iOS
Fixes CB-11287
Tested on iPhones, presenting a modal (camera picker) on landscape mode and dismissing it.
=> CB-11287: (ios) - fix webview resize after modal on iPhones

src/browser/StatusBarProxy.js
Browser.
Fix exception in Browser platform when calling StatusBar.styleDefault() (The error is: ERROR TypeError: win is not a function).
I Ran it in a browser, and it stopped throwing the exception.
(I think this change is too trivial for the below, but I can do it it if necessary)
=> Browser: Check callback exists before calling it

README.md, src/ios/CDVStatusBar.m
iOS
Adds "StatusBarDefaultScrollToTop" option to allow developer to re-enable native scroll-to-top behavior on the WebView
The motivation for this is described here: https://issues.apache.org/jira/browse/CB-13124
=> CB-13124: Add option for native scroll-to-top on WebView

src/ios/CDVStatusBar.m
iOS
Add a small delay we removed so the statusbar size is correct after rotation (it will return 0,0 otherwise) 
Tested on real device
=> CB-13712 (iOS): fix overlaysWebView reset on rotation

README.md
N/A
Updates the README to:
- Add Android as a supported platform for `StatusBarOverlaysWebView` - support for this was added in v2.2.3 but never added to the README
- Remove references to iOS 7 where it is implied to be the latest version of iOS. It's not likely that anyone now cares about iOS 7!
N/A
=> Add Android overlay support to README

README.md
if I understand this correctly, "you can also specify values as #AARRGGBB, where AA is an alpha value." The alpha in this example would be 33% right?
`StatusBar.backgroundColorByHexString('#33000000');`
=> Alpha example doesn't match description

.appveyor.yml, .gitignore, .travis.yml
This is a BREAKING CHANGE.
n/a - development
Drop Node.js v4 support and bumps the CI images to Node.js v6
TravisCI and Appveyor test results.
=> chore: drop Node.js v4 support

README.md
Small documentation change.
Documentation
To make documentation a bit more clear. I was searching online for a way to change the status bar text color and this documentation did not give me that info. I had to resort to trial and error to gain this knowledge.
Small wording change in documentation. Some other alternative might be even better. I decided to mention text color change as an example of effect rather than **the** singular effect, since I am not certain if anything else is changed with that flag/option.
N/A
=> docs(README): Clarify StatusBarStyle

src/ios/CDVStatusBar.m
* iOS (13)
* On iOS 13 the height of the statusbar is set 0 when returning from the camera for example.
* I delayed the call of `resizeWebView` in `cordovaViewWillAppear` by 0.1 seconds according to `statusBarDidChangeFrame`.
* When `resizeWebView` was called to early on resume from the background or the camera for example `statusBarFrame.size.height` was 0. After my changes it was correct in this scenario.
closes https://github.com/apache/cordova-plugin-statusbar/issues/156
- I added automated test coverage as appropriate for this change
- If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- I've updated the documentation if …
=> fix(iOS): Delay resizeWebView on viewWillAppear for correct statusbar height

src/ios/CDVStatusBar.m
ios
Closes #148 
on iOS 13, default depends on the device mode.
This PR forces default to always black.
Tested on iOS 13 device and iOS 11 device on Xcode 10 and 11
=> fix(ios): make default set black text on iOS 13 too

README.md, src/android/StatusBar.java, src/ios/CDVStatusBar.m, www/statusbar.js
Deprecates `blacktranslucent` and `blackopaque` values from `StatusBarStyle` preference, showing a native warning message if set.
Also deprecates `styleBlackTranslucent` and `styleBlackOpaque` functions, showing a javascript warning if used.
Finally, it documents in the README that the preference values and methods are deprecated.
closes #163
=> deprecate blacktranslucent, blackopaque, styleBlackTranslucent and styleBlackOpaque

README.md, plugin.xml, src/android/StatusBar.java
Android
Android never read from `config.xml` for the `StatusBarOverlaysWebView` preference. This PR fixes it so that it reads the preference value, or defaults to true (as dictated by the current documentation)
Fixes #170 
Fixes #151 
Above is pretty much my changes.
There is an existing PR that also addresses this issue at https://github.com/apache/cordova-plugin-statusbar/pull/142 but hasn't had activity since June and hasn't responded to change requests. This PR corrects the issue, with requested changes in mind.
Technically this is a breaking change... as android never obeyed the `StatusBarOverlaysWebView` preference or its defaults, the android default will go from solid statusbar to an overlayed statusbar.
`npm test` and manual testing
=> [do not merge yet](android) Read config.xml for statusbar overlay preference

src/android/StatusBar.java
android
styleDefault is not working on some Android 12/13 devices, this PR makes it work again.
The PR uses `WindowInsetsControllerCompat.setAppearanceLightStatusBars` instead of the deprecated `SYSTEM_UI_FLAG_LIGHT_STATUS_BAR`. Makes `styleDefault` work on new devices.
It's a breaking change because it requires `androidx.core`, which is only available on cordova-android >= 9. At the moment the plugin doesn't have any cordova-android version requirement, so requiring cordova-android >= 9 is breaking.
A separate PR would be sent to set the engines if this PR gets accepted.
closes https://github.com/apache/cordova-plugin-statusbar/issues/236
closes https://github.com/apache/cordova-plugin-statusbar/pull/235, which is a similar PR but uses deprecated methods.
Tested on real devices and …
=> fix(android)!: styleDefault not working on new devices

README.md, src/android/StatusBar.java, src/browser/StatusBarProxy.js, src/ios/CDVStatusBar.h, src/ios/CDVStatusBar.m, src/windows/StatusBarProxy.js, tests/tests.js, types/index.d.ts, www/statusbar.js
all
`blacktranslucent` and `blackopaque` styles and the corresponding methods StatusBar.styleBlackTranslucent and StatusBar.styleBlackOpaque are deprecated. 
Remove them.
Removes the previous deprecated methods that do the same as lightcontent.
=> chore!: remove deprecated methods

src/ios/CDVStatusBar.m
iOS
silences and fixes warnings in code
closes https://github.com/apache/cordova-plugin-statusbar/issues/215
silences deprecation warnings since the code still works (tested on iOS 15) and is only used if `UIViewControllerBasedStatusBarAppearance` is present in the Info.plist and with `NO` value. 
real device and simulator
=> chore(ios): Silence/fix warnings

src/android/StatusBar.java
Since the next major version of the plugin [will require](https://github.com/apache/cordova-plugin-statusbar/pull/241) cordova-android 10, all the kitkat or SDK 21 version checks can be removed since cordova-android 10 supports SDK 22+.
Also the plugin doesn't throws JSONException since the error is catch.
Also replace the Runnable with lambdas.
=> refactor(android): Remove unused code

src/android/StatusBar.java
android
Refactor `setStatusBarStyle` method
`String[]` not necessary.
build test within AS
=> refactor(android): refactor setStatusBarStyle

src/android/StatusBar.java
Android
refactor `setStatusBarBackgroundColor`
`setStatusBarBackgroundColor` use to use reflection so that the project didn't need to be compile with SDK level 21 or higher.
Per plugin's defined cordova-android requirement, in `plugin.xml` and `package.json`, the minimum supported SDK level is 22. Reflection should not be required anymore.
Also, we do not need to type in the hex values anymore on the following lines as SDK 22 is minimum and the `WindowManager.LayoutParams` is available.
```java
window.clearFlags(0x04000000); // SDK 19: WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
window.addFlags(0x80000000); // SDK 21: WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
```
Build with AS
=> refactor(android)!: setStatusBarBackgroundColor

src/android/StatusBar.java
Android
Declare class properties `activity` and `window` to shorten lines and remove in method defines.
Created class properties and defined them plugin initialize.
build with AS
=> refactor(android): simplify window & activity

src/ios/CDVStatusBar.m
iOS
Ref: https://github.com/apache/cordova-ios/pull/1400
Currently this works because of a category extension that adds a `scrollView` method to every UIView instance, but that causes issues for SwiftUI so we want to remove that extension from cordova-ios.
Since we do need to be able to look up the scrollView in this plugin, we can just define a private local method that does the same thing in a way that doesn't pollute global UIKit classes.
=> fix(iOS): Inline code to find the webview's scrollView
